In [91]:
import pandas as pd
import numpy as np
import tensorflow as tf
import sklearn 

In [93]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras import utils as np_untils
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

In [95]:
base = pd.read_csv("iris.csv")

In [97]:
base

sepal length  sepal width  petal length  petal width           class
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [99]:
x = base.iloc[:,0:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [101]:
y = base.iloc[:,4].values
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versic

In [103]:
#transformar as flores em numeros para melhor manipulacao(cada linha um tipo de flor) 
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [105]:
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.utils import to_categorical

# Transformar rótulos em números
label_encoder = LabelEncoder()
y = label_encoder.fit_transform(y)  # Converte rótulos para números inteiros

# Converter para one-hot encoding
y = to_categorical(y)

print("Shape dos rótulos:", y.shape)  # Deve ser (150, 3) para 150 amostras e 3 classes


Shape dos rótulos: (150, 3)


In [107]:
x_treinamento, x_teste, y_treinamento, y_teste =  train_test_split(x,y, test_size = 0.25)

In [109]:
x_treinamento.shape, x_teste.shape

((112, 4), (38, 4))

In [111]:
#3colunas por conta das 3 classes
y_treinamento.shape, y_teste.shape

((112, 3), (38, 3))

In [113]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(4,)),
    tf.keras.layers.Dense(units=4, activation = "relu"), #(4 de entrada + 3 de saida / 2)
    tf.keras.layers.Dense(units=4, activation = "relu"),
    tf.keras.layers.Dense(units=3,activation = "softmax") #3 saidas um para cada iris
])

In [115]:
rede_neural.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4)              │            20 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 55 (220.00 B)

 Trainable params: 55 (220.00 B)

 Non-trainable params: 0 (0.00 B)

In [117]:
rede_neural.compile(optimizer = "Adam", loss="categorical_crossentropy",metrics=["categorical_accuracy"])

In [121]:
rede_neural.fit(x_treinamento, y_treinamento, batch_size=10, epochs=1000)

Epoch 1/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.9278 - loss: 0.3802 
Epoch 2/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.9420 - loss: 0.4082 
Epoch 3/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.9013 - loss: 0.3963 
Epoch 4/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8783 - loss: 0.3797 
Epoch 5/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.9070 - loss: 0.3977 
Epoch 6/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.9418 - loss: 0.3863 
Epoch 7/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8575 - loss: 0.4047 
Epoch 8/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8772 - loss: 0.4109 
Epoch 9/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8488 - loss: 0.3979 
Epoch 10/1000
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - categorical_accuracy: 0.8160 - loss: 0.3844 
Epoch 11/

In [123]:
rede_neural.evaluate(x_teste,y_teste)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - categorical_accuracy: 1.0000 - loss: 0.0244


[0.02308044768869877, 1.0]

In [125]:
#resultado de todas as probabilidades para cada um dos neuronios, por conta das 3 classes(camada de saida)
previsoes = rede_neural.predict(x_teste)
print(previsoes)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[1.26038458e-07 1.36296907e-02 9.86370206e-01]
 [9.99983013e-01 7.75349963e-06 9.31191425e-06]
 [2.52096477e-09 5.37777669e-04 9.99462128e-01]
 [9.99999642e-01 1.09903677e-08 3.65865702e-07]
 [5.23936387e-06 9.95249510e-01 4.74526081e-03]
 [9.45043865e-09 2.15044129e-04 9.99785006e-01]
 [1.42115978e-05 9.21968400e-01 7.80174285e-02]
 [1.59853753e-05 9.99187052e-01 7.96991750e-04]
 [5.74658543e-10 2.34549607e-05 9.99976575e-01]
 [9.99986053e-01 7.14379348e-06 6.81963365e-06]
 [1.28126230e-05 9.99548733e-01 4.38395218e-04]
 [9.99982059e-01 1.01688029e-05 7.82262578e-06]
 [3.69784118e-07 4.99703169e-01 5.00296474e-01]
 [9.99995708e-01 1.03963350e-06 3.21173502e-06]
 [3.63200320e-06 9.99742627e-01 2.53829319e-04]
 [1.29916471e-05 9.99768853e-01 2.18131667e-04]
 [9.99926567e-01 6.06103276e-05 1.28795282e-05]
 [9.99993205e-01 3.88834769e-06 2.91728020e-06]
 [1.92145411e-09 1.65010701e-04 9.99835074e-01]
 [3.16028978e-04 9.99568582e-01 1.15492869e-04]
 [

In [129]:
previsoes = previsoes > 0.5
print(previsoes)

[[False False  True]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False False  True]
 [False  True False]
 [False  True False]
 [False False  True]
 [ True False False]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [False  True False]
 [False  True False]
 [ True False False]
 [ True False False]
 [False False  True]
 [False  True False]
 [ True False False]
 [False False  True]
 [ True False False]
 [ True False False]
 [False  True False]
 [False False  True]
 [False False  True]
 [ True False False]
 [False  True False]
 [ True False False]
 [ True False False]
 [ True False False]
 [ True False False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False  True False]
 [False False  True]]


In [133]:
#comparacao do teste com as previsoes
y_teste2 = [np.argmax(t) for t in y_teste]
print(y_teste2)

[2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 0, 1, 1, 0, 0, 2, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2]


In [135]:
previsoes2 =  [np.argmax(t) for t in previsoes]
print(previsoes2)

[2, 0, 2, 0, 1, 2, 1, 1, 2, 0, 1, 0, 2, 0, 1, 1, 0, 0, 2, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 2]


In [139]:
from sklearn.metrics import accuracy_score

In [141]:
accuracy_score(y_teste2, previsoes2)

1.0

In [145]:
#setosa, vessicolor, virginica (esta nesta ordem na diagonal principal)
confusion_matrix(y_teste2, previsoes2)

array([[15,  0,  0],
       [ 0, 13,  0],
       [ 0,  0, 10]])