In [3]:
import pandas as pd

In [4]:
#base de dados de entrada
x = pd.read_csv("entradas_breast.csv")
x

radius_mean   texture_mean   perimeter_mean   area_mean  \
0           17.99          10.38           122.80      1001.0   
1           20.57          17.77           132.90      1326.0   
2           19.69          21.25           130.00      1203.0   
3           11.42          20.38            77.58       386.1   
4           20.29          14.34           135.10      1297.0   
..            ...            ...              ...         ...   
564         21.56          22.39           142.00      1479.0   
565         20.13          28.25           131.20      1261.0   
566         16.60          28.08           108.30       858.1   
567         20.60          29.33           140.10      1265.0   
568          7.76          24.54            47.92       181.0   

      smoothness_mean   compactness_mean   concavity_mean  \
0             0.11840            0.27760          0.30010   
1             0.08474            0.07864          0.08690   
2             0.10960            0.15990          0.19740   
3             0.14250            0.28390          0.24140   
4             0.10030            0.13280        198.00000   
..                ...                ...              ...   
564         111.00000            0.11590          0.24390   
565           0.09780            0.10340        144.00000   
566           0.08455            0.10230          0.09251   
567           0.11780          277.00000          0.35140   
568           0.05263            0.04362          0.00000   

     concave_points_mean   symmetry_mean   fractal_dimension_mean  ...  \
0                0.14710          0.2419                  0.07871  ...   
1                0.07017          0.1812                  0.05667  ...   
2                0.12790          0.2069                  0.05999  ...   
3                0.10520          0.2597                  0.09744  ...   
4                0.10430          0.1809                  0.05883  ...   
..                   ...             ...                      ...  ...   
564              0.13890          0.1726                  0.05623  ...   
565              0.09791          0.1752                  0.05533  ...   
566              0.05302        159.0000                  0.05648  ...   
567            152.00000          0.2397                  0.07016  ...   
568              0.00000          0.1587                  0.05884  ...   

      radius_worst   texture_worst   perimeter_worst   area_worst  \
0            25.38           17.33            184.60       2019.0   
1            24.99           23.41            158.80       1956.0   
2            23.57           25.53            152.50       1709.0   
3            14.91           26.50             98.87        567.7   
4            22.54           16.67            152.20       1575.0   
..             ...             ...               ...          ...   
564          25.45           26.40            166.10       2027.0   
565          23.69           38.25            155.00       1731.0   
566          18.98           34.12            126.70       1124.0   
567          25.74           39.42            184.60       1821.0   
568        9456.00           30.37             59.16        268.6   

      smoothness_worst   compactness_worst   concavity_worst  \
0              0.16220             0.66560            0.7119   
1              0.12380             0.18660            0.2416   
2              0.14440             0.42450            0.4504   
3              0.20980             0.86630            0.6869   
4              0.13740           205.00000            0.4000   
..                 ...                 ...               ...   
564          141.00000             0.21130            0.4107   
565            0.11660             0.19220            0.3215   
566            0.11390             0.30940            0.3403   
567          165.00000             0.86810            0.9387   
568            0.08996             0.06444            0.0000   

     

In [11]:
#base da dados da saida
y = pd.read_csv("saidas_breast.csv")
y

0
0    0
1    0
2    0
3    0
4    0
..  ..
564  0
565  0
566  0
567  0
568  1

[569 rows x 1 columns]

In [40]:
#biblioteca responsavel pelo treiamento da maquina
import sklearn
from sklearn.model_selection import train_test_split

In [41]:
#decidindo as varivaies q iremos utilizar com o x e y (treinamento e teste), com a porcentagem de teste pre definida
x_treinamento, x_teste, y_treinamento, y_teste = train_test_split(x,y,test_size = 0.25)

In [42]:
x_treinamento.shape, y_treinamento.shape

((426, 30), (426, 1))

In [43]:
x_teste.shape, y_teste.shape

((143, 30), (143, 1))

In [44]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

In [45]:
(30 + 1) / 2

15.5

In [83]:
rede_neural = Sequential([
    tf.keras.layers.InputLayer(shape=(30,)),  # usando 'shape' ao invés de 'input_shape' por conta de um erro
    tf.keras.layers.Dense(units=16, activation="relu", kernel_initializer="random_uniform"),  # neurônios na camada oculta
    tf.keras.layers.Dense(units=16, activation="relu",kernel_initializer="random_uniform"),#mais uma camada oculta
    tf.keras.layers.Dense(units=1, activation="sigmoid")  # uma saída, portanto sigmoid
])


In [85]:
30*16, 496-480 #foi adcionado a undiade de BIAS

(480, 16)

In [87]:
rede_neural.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 16)             │           272 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 785 (3.07 KB)

 Trainable params: 785 (3.07 KB)

 Non-trainable params: 0 (0.00 B)

In [109]:
otimizador = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=0.5)

In [111]:
#treinamento da rede neural
rede_neural.fit(x_treinamento,y_treinamento, batch_size = 10, epochs = 100) #10 em 10 registros = 1 batch

Epoch 1/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 877us/step - binary_accuracy: 0.9241 - loss: 0.1475
Epoch 2/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - binary_accuracy: 0.9577 - loss: 0.1036
Epoch 3/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 653us/step - binary_accuracy: 0.9621 - loss: 0.1214
Epoch 4/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 646us/step - binary_accuracy: 0.9406 - loss: 0.1226
Epoch 5/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 707us/step - binary_accuracy: 0.9377 - loss: 0.1400
Epoch 6/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 632us/step - binary_accuracy: 0.9439 - loss: 0.1336
Epoch 7/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 712us/step - binary_accuracy: 0.9722 - loss: 0.0826
Epoch 8/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 688us/step - binary_accuracy: 0.9614 - loss: 0.1233
Epoch 9/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 665us/step - binary_accuracy: 0.9277 - loss: 0.1542
Epoch 10/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 692us/step - binary_accuracy: 0.9437 - loss: 0.1383
Epoch 11/100
43/43 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - binar

In [128]:
pesos0 = rede_neural.layers[0].get_weights()
pesos0

[array([[-5.94162755e-02, -2.41037041e-01,  4.10017759e-01,
          2.31818501e-02, -2.88539287e-02,  2.43682876e-01,
          7.07346648e-02,  2.58070920e-02, -1.40611231e-01,
         -3.15300487e-02,  3.05366684e-02,  4.00888100e-02,
         -1.08958229e-01,  1.21974804e-01, -5.74833639e-02,
         -4.07798961e-02],
        [-2.14229394e-02, -3.39873254e-01,  6.11189939e-02,
          1.52344946e-02, -2.50563864e-02,  7.02372640e-02,
         -1.83062907e-02, -1.80090114e-01,  1.22272698e-02,
          2.71001216e-02, -3.35903801e-02,  2.08689980e-02,
          1.60273820e-01, -8.16716813e-03, -1.46657992e-02,
          2.43042037e-02],
        [-1.16716931e-03, -1.52007833e-01,  3.44437599e-01,
         -2.92779859e-02,  1.15388855e-02,  2.35734150e-01,
          2.38406271e-01, -2.64178693e-01, -3.71466160e-01,
         -5.57028968e-03,  4.50014099e-02,  4.39895056e-02,
         -3.52991253e-01,  2.82471985e-01,  1.50704896e-03,
         -3.03368899e-03],
        [-1.0786446

In [132]:
pesos1 = rede_neural.layers[1].get_weights()
pesos1

[array([[-9.40175131e-02,  1.30913794e-01, -6.56347871e-02,
         -3.78230214e-02,  4.78865318e-02,  8.73057842e-02,
         -5.72309978e-02, -1.24288633e-01, -2.91599873e-02,
         -2.99566127e-02, -1.13683417e-02, -3.67423557e-02,
          6.62159845e-02,  4.58570868e-02,  1.12217732e-01,
         -9.04446542e-02],
        [ 4.68435064e-02, -1.03349835e-02,  2.04988066e-02,
         -5.29845953e-02, -1.25689119e-01, -1.00225545e-01,
          5.66574223e-02,  8.84450972e-02, -1.18257096e-02,
         -4.03004438e-02, -2.06597298e-01, -8.32374394e-02,
         -1.18280262e-01, -1.28291979e-01, -6.88691437e-02,
          9.45350006e-02],
        [-3.66697907e-02,  3.65411676e-02,  8.74900594e-02,
          1.26242554e-02, -1.47031695e-01,  4.58484665e-02,
          3.21989357e-02, -1.07704215e-01,  1.27308533e-01,
          9.93575901e-03, -1.57276762e-03,  1.01430877e-03,
          1.18771799e-01,  9.00309533e-04, -3.75058353e-02,
         -8.90645534e-02],
        [ 3.7178091

In [134]:
len(pesos1)

2

In [136]:
pesos2 = rede_neural.layers[2].get_weights()
pesos2

[array([[-0.40984508],
        [ 0.1551447 ],
        [-0.17358765],
        [-0.25741753],
        [ 0.50937253],
        [ 0.5053271 ],
        [-0.49259505],
        [-0.24560806],
        [ 0.30268273],
        [-0.11852477],
        [ 0.13774413],
        [ 0.01238967],
        [ 0.45709503],
        [ 0.17936774],
        [ 0.00404047],
        [-0.23507743]], dtype=float32),
 array([0.75934464], dtype=float32)]

In [138]:
len(pesos2)

2

In [130]:
#2 arrays, um pesos entre a camda de entrada com a oculta, e o peso das unidade de bias que apontam para a camada oculta
len(pesos0)

2

In [113]:
previsoes = rede_neural.predict(x_teste)
previsoes = previsoes > 0.5

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 


In [115]:
previsoes

array([[False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [117]:
y_teste

0
244  0
184  0
284  1
180  0
497  1
..  ..
186  0
45   0
161  0
369  0
225  1

[143 rows x 1 columns]

In [119]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [121]:
#percentual de acerto da rede neural dos registros
accuracy_score(y_teste, previsoes)

0.9230769230769231

In [123]:
#quantidade de registros certos, somando a diagonal para quantidade de acertos
confusion_matrix(y_teste,previsoes)

array([[44,  8],
       [ 3, 88]])

In [125]:
#valor do erro e o valor do acerto(accuracy)
rede_neural.evaluate(x_teste,y_teste)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - binary_accuracy: 0.9301 - loss: 0.2482 


[0.2541980445384979, 0.9230769276618958]